[phases.setup]
nixPkgs = ["dotnetCorePackages.sdk_8_0"]

[phases.install]
cmds = ["dotnet restore SecureShop.API/SecureShop.API.csproj -r linux-x64"]

[phases.build]
cmds = ["dotnet publish SecureShop.API/SecureShop.API.csproj -c Release -r linux-x64 --self-contained true -o out && chmod +x out/SecureShop.API && chmod +x start.sh"]

[start]
cmd = "bash /app/start.sh"
